Start migration off defaults to conda-forge channel (#4126)
Summary:

Good resource on overriding channels to make sure we aren't using `defaults`:https://stackoverflow.com/questions/67695893/how-do-i-completely-purge-and-disable-the-default-channel-in-anaconda-and-switch

Explanation of changes:
-
- Python upgraded to 3.12 because otherwise we fail with the below error, and I thought we might want to keep telemetry? Let me know otherwise
```
LibMambaUnsatisfiableError: Encountered problems while solving:
  - package conda-anaconda-telemetry-0.1.1-py312h06a4308_0 requires python >=3.12,<3.13.0a0, but none of the providers can be installed

Could not solve for environment specs
The following packages are incompatible
├─ conda-anaconda-telemetry is installable and it requires
│  └─ python >=3.12,<3.13.0a0 , which can be installed;
└─ python 3.11**  is not installable because it conflicts with any installable versions previously reported.
```
- Solver changes: https://github.com/conda/conda-libmamba-solver/issues/283#issue-1903412567 We need to manually install libmamba from conda-forge instead of defaults, then use it. If it and libarchive come from different channels, build fails with:
```
Error while loading conda entry point: conda-libmamba-solver (libarchive.so.20: cannot open shared object file: No such file or directory)

CondaValueError: You have chosen a non-default solver backend (libmamba) but it was not recognized. Choose one of: classic
```
or the very cryptic: (it refers to glibc version...)
```
Your installed version is: 2.35
```
- Why not use the classic solver, why do we need the above change to keep using libmamba? classic is not able to resolve dependencies for us. Others suggest just to use libmamba: https://github.com/conda/conda-build/issues/5516#issuecomment-2521252024. Classic fails with
```
DependencyNeedsBuildingError: Unsatisfiable dependencies for platform linux-64: {'__glibc', '__archspec', '__unix', '__conda', '__linux'}
```
- cpuinfo.py copied in because Python 3.12 removes distutils, and setuptools does not have feature parity. People have complained that they can't use FAISS with Python > 3.11 before and this is the dependency that I see. https://github.com/facebookresearch/faiss/issues/3936
- cuda-toolkit upgraded to 12.5.1 because of this error on 12.4.1:
```
nvlink fatal : Input file
  '/home/runner/miniconda3/bin/../lib/libcudadevrt.a:cuda_device_runtime.o'
  newer than toolkit (126 vs 124)
```
-

Differential Revision: D68043874