Remove unused variable
Summary:
We have a toolchain which some builds seems to have included this dependency recently. For some reason it's causing failures, notably because of this unused variable:

```counterexample,name=failed build
[kevinhui@devvm27613.ftw0 ~/fbsource/fbcode (23b15f2f1a|remote/master)]$ buck2 bxl "fbcode//mode/opt" -c "build_info.host=c7e6-1338-0004-0000.twshared53890.02.lla3.tw.fbinfra.net" -c "build_info.package_name=lxc.whatsapp.theia.orchestrator.sandbox.debug" -c "build_info.package_release=release" -c "build_info.package_version=894ee5d7840dcdbf97803ce3ba1527b7" -c "build_info.revision=5a6f67f1e7fe1c89065f857b96c905c18abe265e" -c "build_info.revision_epochtime=1763996479" -c "build_info.target_path=fbcode//whatsapp/theia/tee/src/cvm/orchestrator/sandbox:lxc.whatsapp.theia.orchestrator.sandbox.debug" -c "build_info.upstream_revision=23b15f2f1a532a8d40fb93361061c8222d33327e" -c "build_info.upstream_revision_epochtime=1763995982" -c "build_info.user=root" -c "fbcode.build_info=stable" -c "fbcode.dwp=true" -c "fbcode.xar_compression_level=16" -c "fbcode.arch=x86_64" "fbcode//registry/builder/build.bxl:build" --build-report "/data/sandcastle/temp/skycastle/.tmpUNSroF" -- --use_verbose_output=true --target "fbcode//whatsapp/theia/tee/src/cvm/orchestrator/sandbox:lxc.whatsapp.theia.orchestrator.sandbox.debug[tree]" --target "fbcode//whatsapp/theia/tee/src/cvm/orchestrator/sandbox:lxc.whatsapp.theia.orchestrator.sandbox.debug[scribe_cat]" --target "fbcode//whatsapp/theia/tee/src/cvm/orchestrator/sandbox:lxc.whatsapp.theia.orchestrator.sandbox.debug[build_ids]" --variants "{\"architecture\":\"x86_64\",\"accelerator\":null}"
{
  "fbcode//whatsapp/theia/tee/src/cvm/orchestrator/sandbox:lxc.whatsapp.theia.orchestrator.sandbox.debug[tree]": [
    {
      "accelerator": null,
      "architecture": "x86_64",
      "output": "buck-out/v2/gen/fbcode/51be0df3abcf8740/whatsapp/theia/tee/src/cvm/orchestrator/sandbox/__lxc.whatsapp.theia.orchestrator.sandbox.debug__/standalone/tree"
    }
  ],
  "fbcode//whatsapp/theia/tee/src/cvm/orchestrator/sandbox:lxc.whatsapp.theia.orchestrator.sandbox.debug[scribe_cat]": [
    {
      "accelerator": null,
      "architecture": "x86_64",
      "output": "buck-out/v2/gen/fbcode/51be0df3abcf8740/whatsapp/theia/tee/src/cvm/orchestrator/sandbox/__lxc.whatsapp.theia.orchestrator.sandbox.debug__/category_to_samples"
    }
  ],
  "fbcode//whatsapp/theia/tee/src/cvm/orchestrator/sandbox:lxc.whatsapp.theia.orchestrator.sandbox.debug[build_ids]": [
    {
      "accelerator": null,
      "architecture": "x86_64",
      "output": "buck-out/v2/gen/fbcode/51be0df3abcf8740/whatsapp/theia/tee/src/cvm/orchestrator/sandbox/__lxc.whatsapp.theia.orchestrator.sandbox.debug__/build_ids.json"
    }
  ]
}
Action failed: fbcode//faiss:faiss (cxx_compile index_factory.cpp (pic))
Remote command returned non-zero exit code 1
Reproduce locally: `frecli cas download-action 0bda7fa291272164aa05567adae07bc25e3c41e7ea4a573f14413540b63587d4:145`
stdout:
stderr:
fbcode/faiss/index_factory.cpp:196:19: error: unused variable 'rabitq_pattern' [-Werror,-Wunused-const-variable]
  196 | const std::string rabitq_pattern = "(RaBitQ)";
      |                   ^~~~~~~~~~~~~~
1 error generated.
Error: command failed
create_dir_all(/data/sandcastle/temp/skycastle)

Caused by:
    Permission denied (os error 13)
Buck UI: https://www.internalfb.com/buck2/28ccbaf8-d0be-498d-b671-1bd85a60423e
Network: Up: 3.2MiB  Down: 871MiB  (reSessionID-c1db63d9-5133-4daf-aff5-e4313796c6e6)
Loading targets.   Remaining      0/46764                                                              129632 dirs read, 1112926 targets declared
Analyzing targets. Remaining      0/183358                                                             944809 actions, 1075889 artifacts declared
Executing actions. Remaining      0/196171                                                             2:34:19.2s exec time total
Command: bxl.      Finished 275 local, 1543 remote, 4568 cache (72% hit)                               1:24:19.9s exec time cached (54%)                                    
Time elapsed: 1:59.5s
BXL FAILED
[kevinhui@devvm27613.ftw0 ~/fbsource/fbcode (23b15f2f1a|remote/master)]$ 
```

A quick `fbgs` shows that this is the only variable in your directory: https://fburl.com/code/uoh6rnu3, so hopefully should be fine to build.

Reviewed By: henrywang8atfbdotcom

Differential Revision: D87786317