Adding [[fallthrough]] annotation to case statements in faiss/utils/hamming_distance/neon-inl.h
Summary:
Error: https://www.internalfb.com/sandcastle/workflow/1661828262501424314
Due to a recent change (D52393687) to increase compiler warnings arcoss faiss/PACKAGE aggregator build is failing. The annotation [[fallthrough]]; needs to be used in every [nested]case statement where fallthrough can occur.

WHAT I DIDNT DO
I did NOT EXPORTED TO OSS FAISS
mdouze please do this if it is required. I do not know your policy. Prior to landing i saw the message but was unsure. As well as not having github account.

Reviewed By: r-barnes

Differential Revision: D52420730

fbshipit-source-id: 92ec8382226ea35bdacb668b3c329bd8b41a67fc