fix open source CI (#3878)
Summary:
Pull Request resolved: https://github.com/facebookresearch/faiss/pull/3878

Looks like D63013820 broke external CI (example failures: https://github.com/facebookresearch/faiss/actions/runs/10965502942/job/30451466102 and https://github.com/facebookresearch/faiss/actions/runs/10964917863 )

with stacktrace
```
Traceback (most recent call last):
  File "/home/runner/work/faiss/faiss/build/faiss/python/setup.py", line 16, in <module>
    shutil.copytree("contrib/torch", "faiss/contrib/torch")
  File "/home/runner/miniconda3/lib/python3.11/shutil.py", line 573, in copytree
    return _copytree(entries=entries, src=src, dst=dst, symlinks=symlinks,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/miniconda3/lib/python3.11/shutil.py", line 471, in _copytree
    os.makedirs(dst, exist_ok=dirs_exist_ok)
  File "<frozen os>", line 225, in makedirs
FileExistsError: [Errno 17] File exists: 'faiss/contrib/torch'
```

`faiss/contrib/torch'` should be copied over from the line above `faiss/contrib`

Reviewed By: asadoughi

Differential Revision: D63145404